// Generated by CoffeeScript 1.7.1
'use strict';
exports.cleanTrack = function(track) {
  delete track.votes;
  delete track.votesHash;
  delete track.updated;
  return track;
};

exports.search = function(m, query, done) {
  var gotError, gotResults, promise;
  promise = m.library.search({
    any: query
  });
  gotResults = function(results) {
    var instances, searchResults, tracks, _i, _len;
    tracks = [];
    instances = [];
    for (_i = 0, _len = results.length; _i < _len; _i++) {
      searchResults = results[_i];
      tracks.push.apply(tracks, searchResults.tracks);
    }
    done(null, tracks);
    results = tracks = null;
  };
  gotError = function(err) {
    return done(err);
  };
  return promise.then(gotResults, gotError);
};

exports.onError = function(err) {
  console.error(err.stack);
};

exports.clear = function(m, done) {
  var gotCurrentTrack, gotIndex, gotPrevious, gotTracks, onError, onRemove, s;
  s = {};
  onError = function(err) {
    done(err);
    s = null;
  };
  gotCurrentTrack = function(tlTrack) {
    if (tlTrack) {
      m.tracklist.index(tlTrack).then(gotIndex, onError);
    } else {
      gotPrevious([]);
    }
  };
  gotIndex = function(index) {
    s.current = index;
    if (0 >= index) {
      gotPrevious([]);
    } else {
      m.tracklist.slice(0, index).then(gotPrevious, onError);
    }
  };
  gotPrevious = function(tlTracks) {
    s.previous = tlTracks;
    m.tracklist.slice(s.current + 1, Infinity).then(gotTracks, onError);
  };
  gotTracks = function(tracks) {
    var ids, track;
    tracks || (tracks = []);
    tracks.push.apply(tracks, s.previous);
    ids = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = tracks.length; _i < _len; _i++) {
        track = tracks[_i];
        _results.push(track.tlid);
      }
      return _results;
    })();
    m.tracklist.remove({
      tlid: ids
    }).then(onRemove, onError);
    s = ids = tracks = null;
  };
  onRemove = function() {
    return done();
  };
  return m.playback.getCurrentTlTrack().then(gotCurrentTrack, onError);
};

exports.setNextTrack = function(m, track, done) {
  var onAdd, onClear, onError;
  onError = function(err) {
    return done(err);
  };
  exports.cleanTrack(track);
  onClear = function(err) {
    if (err) {
      return done(err);
    }
    m.tracklist.add([track], null).then(onAdd, onError);
  };
  onAdd = function() {
    return done();
  };
  return exports.clear(m, onClear);
};
