// Generated by CoffeeScript 1.7.1
'use strict';
var Adapter, redis;

redis = require('redis');

Adapter = require('../lib/redis-adapter.js');

module.exports = function(app) {
  app.set('redis', redis.createClient(app.set('redis port'), app.set('redis host')));
  return app.set('db', new Adapter(app.set('redis'), app.set('redis prefix')));
};
