// Generated by CoffeeScript 1.7.1
'use strict';
var express, mpath;

express = require('express');

mpath = require('path');

module.exports = function(app) {
  app.set('public', mpath.resolve(mpath.join(__dirname, '../public')));
  app.use(express.logger());
  app.use(express.compress());
  return app.use(express["static"](app.set('public')));
};
