// Generated by CoffeeScript 1.7.1
'use strict';
var HomeController, MopidyController;

HomeController = require('../controllers/home.js');

MopidyController = require('../controllers/mopidy.js');

module.exports = function(app) {
  var home, mopidy;
  mopidy = new MopidyController(app);
  home = new HomeController(app);
  app.set('mopidy controller', mopidy);
  return app.get('/', home.route('index'));
};
