// Generated by CoffeeScript 1.9.3
var dnode;

dnode = require('dnode');

module.exports = function(app) {
  var api, shoe;
  shoe = app.set('shoe');
  api = require('../lib/dnode.js')(app);
  return shoe.on('connection', function(stream) {
    var d;
    d = dnode(api, {
      weak: false
    });
    d.stream = stream;
    return d.pipe(stream).pipe(d);
  });
};
