// Generated by CoffeeScript 1.7.1
'use strict';
var Mopidy;

Mopidy = (function() {
  function Mopidy(data) {
    this.data = data;
  }

  Mopidy.prototype.toJSON = function() {
    return this.data;
  };

  return Mopidy;

})();

module.exports = Mopidy;
