// Generated by CoffeeScript 1.7.1
'use strict';
var Album, Mopidy, Track,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Mopidy = require('./mopidy.js');

Album = require('./album.js');

Track = (function(_super) {
  __extends(Track, _super);

  function Track(data) {
    Track.__super__.constructor.call(this, data);
  }

  return Track;

})(Mopidy);

module.exports = Track;
